<?php
/**
 * ReplaceRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZingleApi\UrlShortner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zingle Url Shortner
 *
 * Shortens URLs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ZingleApi\UrlShortner\Model;

use \ArrayAccess;
use \ZingleApi\UrlShortner\ObjectSerializer;

/**
 * ReplaceRequest Class Doc Comment
 *
 * @category Class
 * @package  ZingleApi\UrlShortner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReplaceRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReplaceRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'target_urls' => 'array',
        'vendor' => '\ZingleApi\UrlShortner\Model\Vendor',
        'text' => 'string',
        'prefer_vedor' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'target_urls' => null,
        'vendor' => null,
        'text' => null,
        'prefer_vedor' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'target_urls' => 'targetUrls',
        'vendor' => 'vendor',
        'text' => 'text',
        'prefer_vedor' => 'preferVedor'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'target_urls' => 'setTargetUrls',
        'vendor' => 'setVendor',
        'text' => 'setText',
        'prefer_vedor' => 'setPreferVedor'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'target_urls' => 'getTargetUrls',
        'vendor' => 'getVendor',
        'text' => 'getText',
        'prefer_vedor' => 'getPreferVedor'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['target_urls'] = isset($data['target_urls']) ? $data['target_urls'] : null;
        $this->container['vendor'] = isset($data['vendor']) ? $data['vendor'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['prefer_vedor'] = isset($data['prefer_vedor']) ? $data['prefer_vedor'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets target_urls
     *
     * @return array|null
     */
    public function getTargetUrls()
    {
        return $this->container['target_urls'];
    }

    /**
     * Sets target_urls
     *
     * @param array|null $target_urls target_urls
     *
     * @return $this
     */
    public function setTargetUrls($target_urls)
    {
        $this->container['target_urls'] = $target_urls;

        return $this;
    }

    /**
     * Gets vendor
     *
     * @return \ZingleApi\UrlShortner\Model\Vendor|null
     */
    public function getVendor()
    {
        return $this->container['vendor'];
    }

    /**
     * Sets vendor
     *
     * @param \ZingleApi\UrlShortner\Model\Vendor|null $vendor vendor
     *
     * @return $this
     */
    public function setVendor($vendor)
    {
        $this->container['vendor'] = $vendor;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets prefer_vedor
     *
     * @return bool|null
     */
    public function getPreferVedor()
    {
        return $this->container['prefer_vedor'];
    }

    /**
     * Sets prefer_vedor
     *
     * @param bool|null $prefer_vedor prefer_vedor
     *
     * @return $this
     */
    public function setPreferVedor($prefer_vedor)
    {
        $this->container['prefer_vedor'] = $prefer_vedor;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


