<?php
/**
 * ReplaceRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZingleApi\UrlShortner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zingle Url Shortner
 *
 * Shortens URLs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ZingleApi\UrlShortner;

use PHPUnit\Framework\TestCase;

/**
 * ReplaceRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ReplaceRequest
 * @package     ZingleApi\UrlShortner
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReplaceRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReplaceRequest"
     */
    public function testReplaceRequest()
    {
    }

    /**
     * Test attribute "target_urls"
     */
    public function testPropertyTargetUrls()
    {
    }

    /**
     * Test attribute "vendor"
     */
    public function testPropertyVendor()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "prefer_vedor"
     */
    public function testPropertyPreferVedor()
    {
    }
}
